apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-efs-provisioner
subjects:
  - kind: ServiceAccount
    name: efs-role
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io